# Generated by Django 2.2 on 2021-08-10 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(default='', max_length=5000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='groupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(default='', max_length=100)),
                ('groupDesc', models.CharField(default='Plz change description....', max_length=5000)),
                ('groupImg', models.ImageField(default='', upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(auto_created=True, default=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('userprofile', models.ImageField(default='', upload_to='image/')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=150, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('last_login', models.DateTimeField(default=datetime.datetime.now)),
                ('auth_token', models.CharField(default='', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_At', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.groupModel')),
                ('userRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=1200)),
                ('file', models.FileField(default='', upload_to='file/')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='chats.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='chats.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='GrpMsges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=1200)),
                ('file', models.FileField(default='', upload_to='file/')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.groupModel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='Admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Profile'),
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_friend', models.BooleanField(default=False)),
                ('is_req', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_user', to='chats.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_user', to='chats.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ForgotPwd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_pwd_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default='', max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Profile')),
            ],
        ),
    ]
