# Generated by Django 3.2.4 on 2021-06-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_profile_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='xyz', max_length=100),
        ),
    ]
