# Generated by Django 3.2.4 on 2021-06-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_auto_20210607_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
