# Generated by Django 3.2.4 on 2021-06-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_auto_20210607_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
