# Generated by Django 2.2.24 on 2021-06-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0017_forgotpwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userprofile',
            field=models.ImageField(default='', upload_to='image/'),
        ),
    ]
