# Generated by Django 2.0 on 2021-06-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0019_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
