# Generated by Django 2.0 on 2021-07-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0032_auto_20210703_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpwd',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='usergroups',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergroups',
            name='userRef',
        ),
        migrations.DeleteModel(
            name='ForgotPwd',
        ),
        migrations.DeleteModel(
            name='groupModel',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserGroups',
        ),
    ]
