# Generated by Django 2.0 on 2021-07-05 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0033_auto_20210705_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPwd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_pwd_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='groupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=100)),
                ('groupDesc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=1200)),
                ('file', models.FileField(default='', upload_to='file/')),
                ('timestamp', models.DateTimeField(default=None)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(auto_created=True, default=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('userprofile', models.ImageField(default='', upload_to='image/')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='xyz', max_length=100)),
                ('email', models.EmailField(default='', max_length=150, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('last_login', models.DateTimeField(default=None)),
                ('auth_token', models.CharField(default='', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_At', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.groupModel')),
                ('userRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='chats.Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='chats.Profile'),
        ),
        migrations.AddField(
            model_name='forgotpwd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Profile'),
        ),
    ]
