# Generated by Django 2.0 on 2021-07-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0034_auto_20210705_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpwd',
            name='user',
        ),
        migrations.DeleteModel(
            name='ForgotPwd',
        ),
    ]
