# Generated by Django 2.0 on 2021-07-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0035_auto_20210705_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPwd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_pwd_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Profile')),
            ],
        ),
    ]
