# Generated by Django 2.0 on 2021-07-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0038_auto_20210705_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpwd',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_At',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=None),
        ),
    ]
