# Generated by Django 2.0 on 2021-07-05 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0040_auto_20210705_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpwd',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 15, 37, 9, 373246)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 15, 37, 9, 373246)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 15, 37, 9, 372319)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 15, 37, 9, 372319)),
        ),
    ]
