# Generated by Django 2.0 on 2021-07-05 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0041_auto_20210705_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpwd',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 15, 37, 27, 248267)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 15, 37, 27, 249255)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 15, 37, 27, 247256)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 15, 37, 27, 247256)),
        ),
    ]
