# Generated by Django 2.0 on 2021-07-05 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0048_auto_20210705_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpwd',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 23, 0, 1, 535508)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 23, 0, 1, 535508)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 23, 0, 1, 535508)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 23, 0, 1, 534578)),
        ),
    ]
