# Generated by Django 2.0 on 2021-07-05 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0059_auto_20210705_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpwd',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 17, 44, 4, 31345, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 17, 44, 4, 32401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 17, 44, 4, 31345, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 17, 44, 4, 31345, tzinfo=utc)),
        ),
    ]
