# Generated by Django 2.0 on 2021-07-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0062_auto_20210705_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
