# Generated by Django 2.0 on 2021-07-14 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0064_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(default='', max_length=5000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
