# Generated by Django 2.0 on 2021-07-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0065_broadcast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
