# Generated by Django 2.0 on 2021-07-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0066_auto_20210715_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_req',
            field=models.BooleanField(default=False),
        ),
    ]
