# Generated by Django 2.0 on 2021-07-15 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0067_auto_20210716_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_friend', models.BooleanField(default=False)),
                ('is_req', models.BooleanField(default=False)),
                ('is_accept', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_user', to='chats.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_user', to='chats.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_friend',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_req',
        ),
    ]
