# Generated by Django 2.0 on 2021-07-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0068_auto_20210716_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='is_accept',
        ),
    ]
