# Generated by Django 2.0 on 2021-07-17 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0069_remove_friends_is_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='Admin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chats.Profile'),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='groupImg',
            field=models.ImageField(default='', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='groupDesc',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='groupName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
