# Generated by Django 2.0 on 2021-07-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0072_auto_20210718_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='usergroups',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergroups',
            name='userRef',
        ),
        migrations.DeleteModel(
            name='groupModel',
        ),
        migrations.DeleteModel(
            name='UserGroups',
        ),
    ]
