# Generated by Django 2.0 on 2021-07-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0074_groupmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='Admin',
        ),
        migrations.DeleteModel(
            name='groupModel',
        ),
    ]
