# Generated by Django 2.0 on 2021-07-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0075_auto_20210718_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(default='', max_length=100)),
                ('groupDesc', models.CharField(default='', max_length=5000)),
                ('groupImg', models.ImageField(default='', upload_to='image/')),
                ('Admin', models.ForeignKey(default=100000, on_delete=django.db.models.deletion.CASCADE, to='chats.Profile')),
            ],
        ),
    ]
