# Generated by Django 2.0 on 2021-07-17 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0078_groupmodel_usergroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='Admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Profile'),
        ),
    ]
