# Generated by Django 2.0 on 2021-07-18 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0079_auto_20210718_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroups',
            name='file',
            field=models.FileField(default='', upload_to='file/'),
        ),
        migrations.AddField(
            model_name='usergroups',
            name='message',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='usergroups',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
