# Generated by Django 2.0 on 2021-07-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0081_auto_20210719_0010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Broadcast',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='grpmsges',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grpmsges',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='usergroups',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergroups',
            name='userRef',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='groupModel',
        ),
        migrations.DeleteModel(
            name='GrpMsges',
        ),
        migrations.DeleteModel(
            name='UserGroups',
        ),
    ]
