# Generated by Django 2.0 on 2021-07-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0085_broadcast_feedback_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Broadcast',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
