# Generated by Django 2.2 on 2021-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0087_broadcast_feedback_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='groupDesc',
            field=models.CharField(default='Plz change description....', max_length=5000),
        ),
    ]
